services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./src/init_data:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    working_dir: /home/node/app/src
    command: "npm start"

volumes:
  group-project:
